platform :ios , '10.0'
use_frameworks!

def shared_pods
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BAFluidView', '~> 0.2'
    pod 'Alamofire', '~> 4.9.1'
    pod 'AlamofireImage', '~> 3.6.0'
    pod 'Device'
    pod 'NVActivityIndicatorView'
    pod 'SwifterSwift'
    pod 'ActiveLabel'
    pod 'IQKeyboardManagerSwift'
    pod 'SideMenu', :git => 'https://github.com/jonkykong/SideMenu.git'
    pod 'BarcodeScanner'
    pod 'Charts'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
    pod 'GooglePlaces'
    pod 'JGProgressHUD', '~> 1.4'
    pod 'SwiftVideoBackground', '~> 3.0'
    pod 'RangeSeekSlider'
    pod 'MSCircularSlider'
    pod 'Firebase/Messaging'
    pod 'GrowingTextView'
    pod 'GhostTypewriter'
end
target "Flipr" do
  shared_pods
end
target "Watr" do
  shared_pods
end


